'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const canvas=$('#map'),ctx=canvas.getContext('2d');
const nodes={
 '01':{x:535,y:330,name:'主楼',type:'teach',model:'大型中庭主教学楼',note:'校园核心教学与通行节点'},'02':{x:585,y:470,name:'中央公园',type:'park',model:'环形水景慢行公园',note:'慢行通道与车辆减速区'},
 '04':{x:425,y:555,name:'体育馆',type:'sport',note:'活动时段通行负载上升'},'05R':{x:255,y:610,name:'行政楼',type:'admin',model:'石材玻璃行政中心',note:'文件与行政物资配送点'},
 '05B':{x:940,y:315,name:'女寝1号',type:'dorm',model:'蓝灰庭院女寝1号',note:'主要宿舍配送终点'},'06':{x:855,y:405,name:'食堂 / 快递站',type:'hub',note:'物流始发站；18:00停止学生取件'},
 '07':{x:850,y:490,name:'男寝1号',type:'dorm',model:'红砖线性男寝1号',note:'主要宿舍配送终点'},'08':{x:805,y:565,name:'男寝2号',type:'dorm',model:'L形庭院男寝2号',note:'主要宿舍配送终点'},
 '09':{x:675,y:610,name:'篮球场',type:'sport',model:'蓝色弧顶半室内篮球馆',note:'运动时段通行负载事件点'},'10':{x:600,y:690,name:'南侧公园',type:'park',model:'生态雨水花园',note:'夜间慢行负载上升'},
 '11':{x:500,y:715,name:'南园',type:'park',model:'宿舍区口袋公园',note:'宿舍区慢行节点'},'12':{x:665,y:715,name:'男寝3号',type:'dorm',model:'阶梯庭院男寝3号',note:'主要宿舍配送终点'},
 '13':{x:720,y:445,name:'超市',type:'market',model:'木结构玻璃市场大厅',note:'即时生活物资订单来源'},'14':{x:665,y:360,name:'教学楼14',type:'teach',model:'银白错位教学楼',note:'专业教学楼；课间通行负载上升'},
 '15':{x:705,y:305,name:'教学楼15',type:'teach',model:'银白错位教学楼',note:'专业教学楼；课间通行负载上升'},'16':{x:820,y:275,name:'教学楼16',type:'teach',model:'木构弧形教学楼',note:'专业教学楼；课间通行负载上升'},
 '17':{x:750,y:235,name:'教学楼17',type:'teach',model:'木构弧形教学楼',note:'专业教学楼；课间通行负载上升'},'18':{x:620,y:205,name:'教学楼18',type:'teach',model:'模块化工程教学楼',note:'专业教学楼；课间通行负载上升'},
 '19':{x:520,y:175,name:'教学楼19',type:'teach',model:'模块化工程教学楼',note:'专业教学楼；课间通行负载上升'},'20':{x:595,y:275,name:'教学楼20',type:'teach',model:'模块化工程教学楼',note:'专业教学楼；课间通行负载上升'},
 '21':{x:490,y:260,name:'教学楼21',type:'teach',model:'模块化工程教学楼',note:'专业教学楼；课间通行负载上升'},'22':{x:470,y:360,name:'北园',type:'park',model:'阶梯学习花园',note:'教学区与体育区连接节点'},
 '23':{x:330,y:405,name:'足球场',type:'sport',model:'蓝白看台校园足球场',note:'大型活动通行负载事件点'},'24':{x:330,y:260,name:'信息楼',type:'info',model:'白色格栅信息中心',note:'智能调度与安全监测中心'},
 '25':{x:415,y:180,name:'排球场',type:'sport',model:'折面膜顶半室内排球馆',note:'体育活动通行节点'}
};
const edgePairs=[['01','02'],['01','14'],['01','20'],['01','22'],['02','04'],['02','10'],['02','13'],['04','05R'],['04','09'],['04','10'],['05R','11'],['05B','06'],['05B','07'],['05B','16'],['06','07'],['06','13'],['06','16'],['07','08'],['07','13'],['08','09'],['08','12'],['08','13'],['09','10'],['10','11'],['11','12'],['13','14'],['14','15'],['15','17'],['15','20'],['16','17'],['17','18'],['18','19'],['18','20'],['19','21'],['19','25'],['20','21'],['21','22'],['21','24'],['22','23'],['23','24'],['24','25']];
const colors={hub:'#f7c84b',market:'#ff9a77',dorm:'#7566d8',teach:'#4a9ee8',admin:'#7e9bb4',park:'#69c482',sport:'#ef7d72',info:'#3fc6b1'};
const buildingSprites={
 silver:Object.assign(new Image(),{src:'assets/buildings/teaching-silver.png'}),
 fins:Object.assign(new Image(),{src:'assets/buildings/information-fins.png'}),
 lab:Object.assign(new Image(),{src:'assets/buildings/engineering-lab.png'}),
 main:Object.assign(new Image(),{src:'assets/buildings/main-teaching-large.png'}),
 admin:Object.assign(new Image(),{src:'assets/buildings/administration-center.png'}),
 femaleDorm:Object.assign(new Image(),{src:'assets/buildings/dorm-female-1.png'}),
 maleDorm1:Object.assign(new Image(),{src:'assets/buildings/dorm-male-1.png'}),
 maleDorm2:Object.assign(new Image(),{src:'assets/buildings/dorm-male-2.png'}),
 maleDorm3:Object.assign(new Image(),{src:'assets/buildings/dorm-male-3.png'}),
 timber:Object.assign(new Image(),{src:'assets/buildings/teaching-timber.png'}),
 market:Object.assign(new Image(),{src:'assets/buildings/market-timber-glass.png'}),
 basketball:Object.assign(new Image(),{src:'assets/buildings/basketball-pavilion.png'}),
 football:Object.assign(new Image(),{src:'assets/buildings/football-mini-stadium.png'}),
 volleyball:Object.assign(new Image(),{src:'assets/buildings/volleyball-pavilion.png'}),
 centralPark:Object.assign(new Image(),{src:'assets/buildings/park-central-water.png'}),
 northPark:Object.assign(new Image(),{src:'assets/buildings/park-north-learning.png'}),
 rainPark:Object.assign(new Image(),{src:'assets/buildings/park-south-rain.png'}),
 pocketPark:Object.assign(new Image(),{src:'assets/buildings/park-south-pocket.png'})
};
const spriteByNode={'01':'main','02':'centralPark','05R':'admin','05B':'femaleDorm','07':'maleDorm1','08':'maleDorm2','09':'basketball','10':'rainPark','11':'pocketPark','12':'maleDorm3',13:'market',14:'silver',15:'silver',16:'timber',17:'timber',18:'lab',19:'lab',20:'lab',21:'lab','22':'northPark','23':'football',24:'fins','25':'volleyball'};
const spriteWidths={main:112,admin:86,femaleDorm:82,maleDorm1:78,maleDorm2:76,maleDorm3:80,market:88,silver:74,timber:78,lab:86,fins:72,basketball:112,football:150,volleyball:108,centralPark:88,northPark:70,rainPark:66,pocketPark:68};
const graph={}; Object.keys(nodes).forEach(k=>graph[k]=[]);
edgePairs.forEach(([a,b])=>{const d=Math.hypot(nodes[a].x-nodes[b].x,nodes[a].y-nodes[b].y);graph[a].push({to:b,d});graph[b].push({to:a,d})});
let seed=24681357;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}
const state={time:975,running:false,speed:4,strategy:'eco',selectedOrder:null,events:new Set(),closed:new Set(),layers:{labels:true,mobility:false,orders:true,traffic:true,security:true},orders:[],vehicles:[],quarantine:[],lastOrderMinute:970,metrics:{energy:0,distance:0,loadedDistance:0,delivered:0,ontime:0,late:0,securityHandled:0,securityMissed:0},view:{scale:1,ox:0,oy:0},drag:null};
const typeLabels={hub:'物流枢纽',market:'商业节点',dorm:'宿舍终点',teach:'教学楼',admin:'行政建筑',park:'公园',sport:'体育设施',info:'调度中心'};
const vehicleSpecs={van:{label:'新能源厢式配送车',capacity:8,speed:8.5,battery:42,rate:.22,color:'#f8c951'},bot:{label:'低速无人配送车',capacity:3,speed:5.5,battery:2.4,rate:.052,color:'#4bd2bd'}};
function edgeKey(a,b){return [a,b].sort().join('|')}
function trafficFactor(a,b,time=state.time){const p=period(time);let f=p.traffic;const busy=[a,b].some(n=>nodes[n].type==='teach'||nodes[n].type==='hub'||nodes[n].type==='dorm');if(busy)f+=p.busy;if(state.events.has('surge'))f+=.16;return Math.max(1,f)}
function dijkstra(start,end,time=state.time){if(start===end)return{path:[start],distance:0};const dist={},prev={},open=new Set(Object.keys(nodes));Object.keys(nodes).forEach(k=>dist[k]=Infinity);dist[start]=0;while(open.size){let u=null;open.forEach(k=>{if(u===null||dist[k]<dist[u])u=k});if(u===null||dist[u]===Infinity)break;open.delete(u);if(u===end)break;for(const e of graph[u]){if(!open.has(e.to)||state.closed.has(edgeKey(u,e.to)))continue;const nd=dist[u]+e.d*trafficFactor(u,e.to,time);if(nd<dist[e.to]){dist[e.to]=nd;prev[e.to]=u}}}if(!Number.isFinite(dist[end]))return{path:[],distance:Infinity};const path=[];for(let u=end;u;u=prev[u]){path.unshift(u);if(u===start)break}return{path,distance:dist[end]}}
function fmtTime(m){m=Math.max(0,Math.round(m));return String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0')}
function period(m){if(m<480)return{name:'清晨低负载',demand:.25,mobility:.3,traffic:1,busy:0};if(m<570)return{name:'上课低负载',demand:.35,mobility:.35,traffic:1,busy:.02};if(m<595)return{name:'课间波峰',demand:.8,mobility:.85,traffic:1.18,busy:.18};if(m<690)return{name:'上课低负载',demand:.35,mobility:.35,traffic:1,busy:.02};if(m<780)return{name:'午间高峰',demand:1,mobility:1,traffic:1.22,busy:.22};if(m<870)return{name:'上课低负载',demand:.35,mobility:.35,traffic:1,busy:.03};if(m<880)return{name:'短课间波峰',demand:.72,mobility:.8,traffic:1.15,busy:.16};if(m<980)return{name:'上课低负载',demand:.4,mobility:.38,traffic:1.02,busy:.04};if(m<1080)return{name:'取件高峰',demand:1.15,mobility:1,traffic:1.28,busy:.25};if(m<1140)return{name:'收尾配送',demand:.15,mobility:.75,traffic:1.12,busy:.12};if(m<1200)return{name:'车辆停运',demand:0,mobility:.7,traffic:1,busy:.05};return{name:'食堂闭店',demand:0,mobility:.2,traffic:1,busy:0}}
function addLog(text,warn=false){const li=document.createElement('li');li.textContent=fmtTime(state.time)+' · '+text;if(warn)li.className='warn';$('#log').prepend(li);while($('#log').children.length>12)$('#log').lastChild.remove()}
function makeVehicle(id,type,node){const s=vehicleSpecs[type],n=nodes[node];return{id,type,currentNode:node,x:n.x,y:n.y,battery:100,load:0,status:'空闲',mission:null,path:[],pathIndex:0,stage:null,capacity:s.capacity,speed:s.speed,batteryKwh:s.battery,rate:s.rate,color:s.color,distance:0,loadedDistance:0,energy:0}}
function reset(){seed=24681357;state.time=975;state.running=false;state.selectedOrder=null;state.events.clear();state.closed.clear();state.quarantine=[];state.orders=[];state.lastOrderMinute=970;state.metrics={energy:0,distance:0,loadedDistance:0,delivered:0,ontime:0,late:0,securityHandled:0,securityMissed:0};state.vehicles=[makeVehicle('E-01','van','06'),makeVehicle('E-02','van','06'),makeVehicle('U-01','bot','06'),makeVehicle('U-02','bot','13'),makeVehicle('U-03','bot','06')];[['06','05B',2,35],['06','07',1,28],['13','08',1,26],['06','12',2,42],['05R','01',1,22],['13','05B',1,30]].forEach((x,i)=>createOrder(...x,'普通',`O-${String(i+1).padStart(2,'0')}`));$('#log').innerHTML='';addLog('仿真重置；已载入工作日16:15订单快照');$$('[data-event]').forEach(b=>b.classList.remove('active'));$('#eventState').textContent='正常';setSecurity();renderAll()}
function createOrder(origin,dest,qty=1,due=35,priority='普通',id=null){const order={id:id||'O-'+String(state.orders.length+state.quarantine.length+1).padStart(2,'0'),origin,dest,qty,weight:+(qty*(1.2+rand()*2.3)).toFixed(1),created:state.time,due:state.time+due,priority,status:'pending',vehicle:null,delivered:null,suspicious:false};state.orders.push(order);return order}
function pendingOrders(){return state.orders.filter(o=>o.status==='pending')}
function routeVehicle(v,dest,stage){const route=dijkstra(v.currentNode,dest);if(!route.path.length){addLog(`${v.id} 无可用路径到达 ${nodes[dest].name}`,true);return false}v.path=route.path;v.pathIndex=1;v.stage=stage;if(route.path.length===1)handleArrival(v);return true}
function assignOrders(v,orders){if(!orders.length||v.status!=='空闲')return false;const qty=orders.reduce((s,o)=>s+o.qty,0);if(qty>v.capacity){addLog(`${v.id} 容量不足，无法装载 ${qty} 件`,true);return false}if(v.battery<16){addLog(`${v.id} 电量不足，已拒绝派单`,true);return false}orders.forEach(o=>{o.status='assigned';o.vehicle=v.id});v.mission={orders:orders.map(o=>o.id),origin:orders[0].origin,dest:orders[0].dest};v.status='前往取货';v.load=0;routeVehicle(v,v.mission.origin,'pickup');addLog(`${v.id} 接收 ${orders.length} 单：${nodes[v.mission.origin].name} → ${nodes[v.mission.dest].name}`);state.selectedOrder=null;renderPanels();return true}
function handleArrival(v){v.currentNode=v.path[v.path.length-1]||v.currentNode;v.x=nodes[v.currentNode].x;v.y=nodes[v.currentNode].y;v.path=[];v.pathIndex=0;if(v.stage==='pickup'){const os=v.mission.orders.map(id=>state.orders.find(o=>o.id===id));v.load=os.reduce((s,o)=>s+o.qty,0);v.status='配送中';routeVehicle(v,v.mission.dest,'delivery')}else if(v.stage==='delivery'){const os=v.mission.orders.map(id=>state.orders.find(o=>o.id===id));os.forEach(o=>{o.status='delivered';o.delivered=state.time;state.metrics.delivered++;if(state.time<=o.due)state.metrics.ontime++;else state.metrics.late++});addLog(`${v.id} 已送达 ${nodes[v.currentNode].name}，完成 ${os.length} 单`);v.mission=null;v.load=0;v.status='空闲';v.stage=null;if(v.battery<25)sendCharge(v)}else if(v.stage==='charge'){v.status=state.events.has('charger')?'等待充电':'充电中';v.stage='charging'}renderAll()}
function sendCharge(v){if(v.currentNode==='06'){v.status=state.events.has('charger')?'等待充电':'充电中';v.stage='charging'}else{v.status='返场充电';routeVehicle(v,'06','charge')}}
function updateVehicle(v,simMinutes){if(v.stage==='charging'){if(!state.events.has('charger')){v.battery=Math.min(100,v.battery+simMinutes*2.3);if(v.battery>=92){v.status='空闲';v.stage=null;addLog(`${v.id} 完成充电`)}}return}if(!v.path.length||v.pathIndex>=v.path.length)return;const target=nodes[v.path[v.pathIndex]],dx=target.x-v.x,dy=target.y-v.y,dist=Math.hypot(dx,dy);const move=Math.min(dist,v.speed*simMinutes);if(dist>0){v.x+=dx/dist*move;v.y+=dy/dist*move;const km=move*.002,loaded=v.stage==='delivery';const loadFactor=1+(v.load/v.capacity)*.22;const edgeFrom=v.path[Math.max(0,v.pathIndex-1)],edgeTo=v.path[v.pathIndex];const traffic=trafficFactor(edgeFrom,edgeTo);const used=km*v.rate*loadFactor*traffic;v.energy+=used;v.distance+=km;if(loaded)v.loadedDistance+=km;v.battery=Math.max(0,v.battery-used/v.batteryKwh*100);state.metrics.energy+=used;state.metrics.distance+=km;if(loaded)state.metrics.loadedDistance+=km}if(move>=dist-.01){v.currentNode=v.path[v.pathIndex];v.x=target.x;v.y=target.y;v.pathIndex++;if(v.pathIndex>=v.path.length)handleArrival(v)}}
function autoDispatch(){const pend=pendingOrders();if(!pend.length){addLog('当前没有待派订单');return}const idle=state.vehicles.filter(v=>v.status==='空闲'&&v.battery>=16);if(!idle.length){addLog('暂无可用车辆',true);return}if(state.strategy==='batch'){const groups={};pend.forEach(o=>{const k=o.origin+'-'+o.dest;(groups[k]??=[]).push(o)});for(const group of Object.values(groups)){const v=idle.find(x=>x.status==='空闲');if(!v)break;const batch=[];let quantity=0;for(const o of group){if(quantity+o.qty<=v.capacity){batch.push(o);quantity+=o.qty}}assignOrders(v,batch)}}else{for(const o of pend){const options=idle.filter(v=>v.status==='空闲');if(!options.length)break;options.sort((a,b)=>vehicleCost(a,o,state.strategy)-vehicleCost(b,o,state.strategy));assignOrders(options[0],[o])}}}
function vehicleCost(v,o,strategy){const pickup=dijkstra(v.currentNode,o.origin).distance,trip=dijkstra(o.origin,o.dest).distance;if(!Number.isFinite(pickup+trip))return Infinity;if(strategy==='nearest')return pickup+trip;const km=(pickup+trip)*.002,energy=km*v.rate*(1+o.qty/v.capacity*.22);const typePenalty=strategy==='eco'?(v.type==='van'&&trip<270?85:0)+(v.type==='bot'&&trip>430?120:0):0;return energy*900+pickup*.3+typePenalty}
function generateOrders(){if(state.time>=1080||state.time>=1140)return;const p=period(state.time);const count=state.events.has('surge')?2:1;for(let i=0;i<count;i++){if(rand()>p.demand*.72)continue;const origins=rand()<.72?['06']:['13','05R','14','18'];const origin=origins[Math.floor(rand()*origins.length)],dests=['05B','07','08','12'];let dest=dests[Math.floor(rand()*dests.length)];if(origin!=='06'&&rand()<.28)dest=['01','14','18','24'][Math.floor(rand()*4)];const priority=rand()>.82?'紧急':'普通';createOrder(origin,dest,1+Math.floor(rand()*2),priority==='紧急'?20:36,priority)}}
function replanMovingVehicles(){let count=0;state.vehicles.forEach(v=>{if(!v.path.length||!v.stage)return;let nearest=v.currentNode,best=Infinity;Object.entries(nodes).forEach(([id,n])=>{const d=Math.hypot(v.x-n.x,v.y-n.y);if(d<best){best=d;nearest=id}});v.currentNode=nearest;const dest=v.stage==='pickup'?v.mission?.origin:v.stage==='delivery'?v.mission?.dest:'06';if(dest){const route=dijkstra(nearest,dest);if(route.path.length){v.path=route.path;v.pathIndex=1;count++}}});return count}
function triggerEvent(name,button){
 const active=state.events.has(name);
 if(name==='surge'&&!active){state.events.add(name);for(let i=0;i<8;i++)createOrder(i<6?'06':'13',['05B','07','08','12'][i%4],1+(i%2),22+i*2,i<2?'紧急':'普通');addLog('订单暴增：新增8条可信订单',true)}
 else if(name==='attack'&&!active){state.events.add(name);const bad={id:'X-'+String(state.quarantine.length+1).padStart(2,'0'),origin:'06',dest:'12',tamperedDest:'05R',qty:3,created:state.time,due:state.time+18,status:'quarantined',suspicious:true,risk:92,reason:'目的地字段与签名摘要不一致'};state.quarantine.push(bad);addLog('安全系统隔离一条目的地被篡改的订单',true);setSecurity(bad)}
 else{
  active?state.events.delete(name):state.events.add(name);
  if(name==='closure'){const k=edgeKey('06','07');active?state.closed.delete(k):state.closed.add(k);const count=replanMovingVehicles();addLog(active?'06—07道路恢复通行':`06—07道路封闭，已为${count}辆在途车辆重算路线`,!active)}
  if(name==='flood'){const k=edgeKey('23','24');active?state.closed.delete(k):state.closed.add(k);const count=replanMovingVehicles();addLog(active?'滨水道路积水消退，23—24恢复通行':`水岸突发积水，23—24封闭，已为${count}辆在途车辆重算路线`,!active)}
  if(name==='charger')addLog(active?'充电设施恢复':'06充电设施故障，低电量车辆进入等待',!active)
 }
 button.classList.toggle('active',state.events.has(name));$('#eventState').textContent=state.events.size?`${state.events.size}项事件`:'正常';renderAll()
}
function reviewAttack(){const bad=state.quarantine.find(o=>o.status==='quarantined');if(!bad)return;bad.status='recovered';state.metrics.securityHandled++;createOrder(bad.origin,bad.dest,bad.qty,24,'紧急','R-'+bad.id.slice(2));state.events.delete('attack');$$('[data-event="attack"]').forEach(b=>b.classList.remove('active'));addLog(`异常订单 ${bad.id} 已校验，恢复可信目的地 ${nodes[bad.dest].name}`);setSecurity();renderAll()}
function setSecurity(bad=null){const q=bad||state.quarantine.find(o=>o.status==='quarantined');$('#reviewAttack').disabled=!q;$('#securityStatus').textContent=q?`风险 ${q.risk}/100`:'无异常';$('#securityDetail').textContent=q?`${q.id}：${q.reason}。声明目的地“${nodes[q.dest].name}”，篡改字段指向“${nodes[q.tamperedDest].name}”。订单已暂停派发。`:'系统校验订单时间、目的地、签名与历史行为。异常订单不会直接进入车辆调度。';const spans=$$('#securityFlow span');spans.forEach(s=>s.className='');if(q){spans[1].className='alert';spans[2].className='alert'}else spans[3].className='safe'}
function estimate(strategy){const pend=pendingOrders();if(!pend.length)return{distance:0,energy:0,ontime:100};let distance=0,energy=0,late=0;const vehicles=state.vehicles.map(v=>({...v}));const groups=strategy==='batch'?Object.values(pend.reduce((a,o)=>{const k=o.origin+'-'+o.dest;(a[k]??=[]).push(o);return a},{})):pend.map(o=>[o]);groups.forEach(g=>{const o=g[0];const options=vehicles.map(v=>({v,c:vehicleCost(v,o,strategy)})).sort((a,b)=>a.c-b.c);const v=options[0].v;let px=dijkstra(v.currentNode,o.origin).distance+dijkstra(o.origin,o.dest).distance;if(strategy==='batch')px*=.82;const km=px*.002;distance+=km;energy+=km*v.rate*(1+Math.min(v.capacity,g.reduce((s,x)=>s+x.qty,0))/v.capacity*.22);const travel=km/(v.type==='van'?.28:.16);if(state.time+travel>Math.min(...g.map(x=>x.due)))late+=g.length;v.currentNode=o.dest});return{distance,energy,ontime:Math.max(0,100-late/pend.length*100)}}
function renderCompare(){const data=['nearest','batch','eco'].map(k=>({k,...estimate(k)})),labels={nearest:'就近优先',batch:'批量优先',eco:'综合优化'};const minD=Math.min(...data.map(x=>x.distance)),minE=Math.min(...data.map(x=>x.energy)),maxO=Math.max(...data.map(x=>x.ontime));$('#compareTable').innerHTML='<div class="compare-row header"><span>策略</span><span>里程</span><span>能耗</span><span>准时率</span></div>'+data.map(x=>`<div class="compare-row"><strong>${labels[x.k]}</strong><span class="compare-cell ${x.distance===minD?'best':''}">${x.distance.toFixed(2)} km</span><span class="compare-cell ${x.energy===minE?'best':''}">${x.energy.toFixed(2)} kWh</span><span class="compare-cell ${x.ontime===maxO?'best':''}">${x.ontime.toFixed(0)}%</span></div>`).join('')}
function score(){const pending=pendingOrders().length,missed=state.quarantine.filter(x=>x.status==='quarantined').length;return Math.max(0,Math.round(1000+state.metrics.delivered*65-state.metrics.late*70-pending*12-state.metrics.energy*16-missed*120))}
function renderPanels(){const pend=pendingOrders();$('#orderCount').textContent=`${pend.length} 条`;$('#orderList').innerHTML=pend.length?pend.slice(0,12).map(o=>`<div class="order-item ${state.selectedOrder===o.id?'selected':''}" data-order="${o.id}"><span class="order-id">${o.id}</span><span class="order-main"><strong>${nodes[o.origin].name} → ${nodes[o.dest].name}</strong><small>${o.qty}件 · ${o.weight}kg · 截止${fmtTime(o.due)}</small></span><span class="priority">${o.priority}</span></div>`).join(''):'<div class="empty">暂无待派订单</div>';$$('[data-order]').forEach(el=>el.onclick=()=>{state.selectedOrder=el.dataset.order;renderPanels()});$('#fleetList').innerHTML=state.vehicles.map(v=>`<div class="fleet-item" data-vehicle="${v.id}"><div class="fleet-top"><span>${v.id} · ${v.type==='van'?'配送车':'无人车'}</span><span>${v.status}</span></div><div class="bars"><div><div class="bar-label"><span>电量</span><span>${v.battery.toFixed(0)}%</span></div><div class="bar energy"><i style="width:${v.battery}%"></i></div></div><div><div class="bar-label"><span>载荷</span><span>${v.load}/${v.capacity}</span></div><div class="bar"><i style="width:${v.load/v.capacity*100}%"></i></div></div></div></div>`).join('');$$('[data-vehicle]').forEach(el=>el.onclick=()=>{const o=state.orders.find(x=>x.id===state.selectedOrder&&x.status==='pending'),v=state.vehicles.find(x=>x.id===el.dataset.vehicle);if(o)assignOrders(v,[o]);else addLog('请先选择一条待派订单')});const delivered=state.metrics.delivered,rate=delivered?state.metrics.ontime/delivered*100:100,empty=state.metrics.distance?100*(1-state.metrics.loadedDistance/state.metrics.distance):0;$('#score').textContent=score().toLocaleString();$('#ontime').textContent=rate.toFixed(0)+'%';$('#pending').textContent=pend.length;$('#energy').textContent=state.metrics.energy.toFixed(2)+' kWh';$('#carbon').textContent=(state.metrics.energy*.5703).toFixed(2)+' kg';$('#emptyRate').textContent=empty.toFixed(0)+'%';$('#autoDispatch').textContent='启动'+({nearest:'就近优先',batch:'批量优先',eco:'综合优化'}[state.strategy])+'调度'}
function renderTime(){const p=period(state.time);$('#simClock').textContent=fmtTime(state.time);$('#periodLabel').textContent=p.name;$('#timeSlider').value=Math.round(state.time/5)*5;$('#scheduleText').textContent=state.time<1080?`${p.name}：通行负载系数 ${p.mobility.toFixed(2)}，订单需求系数 ${p.demand.toFixed(2)}。18:00后停止学生取件。`:state.time<1140?'快递站已停止学生取件；车辆继续完成宿舍配送，19:00停运。':state.time<1200?'配送车辆已停运；食堂继续营业至20:00。':'食堂闭店，今日仿真结束。'}
function drawHeat(n,intensity,color){const g=ctx.createRadialGradient(n.x,n.y,4,n.x,n.y,60*intensity);g.addColorStop(0,color);g.addColorStop(1,'rgba(255,255,255,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(n.x,n.y,60*intensity,0,Math.PI*2);ctx.fill()}
function drawVectorBuilding(n){const w=n.type==='teach'?64:n.type==='sport'?72:58,h=n.type==='dorm'?38:34;ctx.fillStyle='rgba(20,60,80,.18)';ctx.beginPath();ctx.roundRect(-w/2+7,-h/2+9,w,h,7);ctx.fill();ctx.fillStyle=colors[n.type];ctx.beginPath();ctx.roundRect(-w/2,-h/2,w,h,7);ctx.fill();ctx.fillStyle='rgba(255,255,255,.65)';if(['park','sport'].includes(n.type)){ctx.beginPath();ctx.ellipse(0,0,w*.3,h*.28,0,0,Math.PI*2);ctx.fill()}else for(let x=-w/2+9;x<w/2-5;x+=13)ctx.fillRect(x,-h/2+9,7,6);return{w,h}}
function drawBuilding(id,n){ctx.save();ctx.translate(n.x,n.y);const spriteKey=spriteByNode[id],img=spriteKey&&buildingSprites[spriteKey];let top=-24,bottom=24;if(img?.complete&&img.naturalWidth){const w=spriteWidths[spriteKey],h=w*img.naturalHeight/img.naturalWidth;ctx.fillStyle='rgba(18,60,89,.14)';ctx.beginPath();ctx.ellipse(4,8,w*.42,9,0,0,Math.PI*2);ctx.fill();ctx.drawImage(img,-w/2,-h+13,w,h);top=-h+13;bottom=19}else{const size=drawVectorBuilding(n);top=-size.h/2;bottom=size.h/2}if(state.layers.labels){const show=id==='05R'?'05行政':id==='05B'?'05女寝':id;ctx.textAlign='center';ctx.font='800 12px ui-rounded,sans-serif';ctx.lineWidth=4;ctx.strokeStyle='rgba(255,255,255,.92)';ctx.strokeText(show,0,top-5);ctx.fillStyle='#123c59';ctx.fillText(show,0,top-5);ctx.font='700 11px ui-rounded,sans-serif';ctx.strokeText(n.name,0,bottom+15);ctx.fillText(n.name,0,bottom+15)}ctx.restore()}
function drawVehicle(v){ctx.save();ctx.translate(v.x,v.y);ctx.fillStyle='rgba(17,55,78,.18)';ctx.beginPath();ctx.ellipse(0,11,16,5,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=v.color;ctx.beginPath();ctx.roundRect(-15,-9,30,18,7);ctx.fill();ctx.fillStyle='#e9fbff';ctx.fillRect(-7,-5,14,7);ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(-9,9,4,0,Math.PI*2);ctx.arc(9,9,4,0,Math.PI*2);ctx.fill();ctx.fillStyle='#123c59';ctx.font='800 10px sans-serif';ctx.textAlign='center';ctx.fillText(v.id,0,-14);ctx.restore()}
function clamp01(v){return Math.max(0,Math.min(1,v))}
function mixColor(a,b,t){const parse=c=>c.startsWith('#')?c.slice(1).match(/.{2}/g).map(x=>parseInt(x,16)):(c.match(/\d+/g)||[0,0,0]).slice(0,3).map(Number);t=clamp01(t);const pa=parse(a),pb=parse(b);return`rgb(${pa.map((v,i)=>Math.round(v+(pb[i]-v)*t)).join(',')})`}
function sceneTone(){const dawn=clamp01((state.time-390)/150),night=clamp01((state.time-1050)/150);return{night,ground:mixColor(mixColor('#cfdcb8','#c8e5c7',dawn),'#78938f',night),lawn:mixColor('#dcefc6','#8cac99',night),forest:mixColor('#68a982','#456e68',night),water:mixColor('#82d1df','#547c98',night),road:mixColor('#f5f3e9','#b9c4c5',night)}}
function terrainBlob(x,y,rx,ry,color){ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill()}
function drawTree(x,y,s,now,tone,index){const sway=Math.sin(now*.75+index*1.37)*1.5;ctx.fillStyle=mixColor('#8b7855','#465d58',tone.night);ctx.fillRect(x-1,y+3,3,s*1.15);ctx.fillStyle='rgba(20,73,58,.16)';ctx.beginPath();ctx.ellipse(x+5,y+s*.85,s*1.05,s*.36,-.12,0,Math.PI*2);ctx.fill();terrainBlob(x+sway,y,s*1.05,s*.72,tone.forest);terrainBlob(x-3+sway,y-3,s*.62,s*.5,mixColor('#83c990','#5f8173',tone.night))}
function drawTerrain(now){
 const tone=sceneTone(),g=ctx.createLinearGradient(0,0,0,760);g.addColorStop(0,mixColor(tone.ground,'#e6f0d4',.28));g.addColorStop(1,tone.ground);ctx.fillStyle=g;ctx.fillRect(-200,-200,1600,1160);
 // 校园用地边界与不规则功能绿地。
 ctx.fillStyle=tone.lawn;ctx.beginPath();ctx.moveTo(170,92);ctx.bezierCurveTo(360,38,760,45,1032,112);ctx.bezierCurveTo(1125,250,1138,545,1025,690);ctx.bezierCurveTo(805,755,430,765,178,674);ctx.bezierCurveTo(118,492,116,260,170,92);ctx.closePath();ctx.fill();ctx.strokeStyle='rgba(255,255,255,.55)';ctx.lineWidth=4;ctx.stroke();
 // 西侧生态水岸，缩窄后保留事件扩展空间。
 ctx.fillStyle=tone.water;ctx.beginPath();ctx.moveTo(-70,55);ctx.bezierCurveTo(54,75,129,142,116,236);ctx.bezierCurveTo(97,365,140,510,61,776);ctx.lineTo(-120,790);ctx.closePath();ctx.fill();
 ctx.strokeStyle=mixColor('#dff9f7','#a8c8d5',tone.night);ctx.lineWidth=9;ctx.beginPath();ctx.moveTo(38,72);ctx.bezierCurveTo(121,124,137,164,116,242);ctx.bezierCurveTo(95,366,135,508,62,759);ctx.stroke();
 ctx.save();ctx.strokeStyle='rgba(255,255,255,.45)';ctx.lineWidth=2;ctx.setLineDash([26,30]);ctx.lineDashOffset=-(now*13)%56;[0,1,2].forEach(i=>{ctx.beginPath();ctx.moveTo(18+i*22,100);ctx.bezierCurveTo(89+i*12,205,74+i*17,405,31+i*18,705);ctx.stroke()});ctx.restore();
 // 建筑组团铺装和公园用地，均采用自然曲线而非矩形占位块。
 ctx.fillStyle=mixColor('#e6e1ce','#9caead',tone.night);[[470,295,170,118],[730,320,245,170],[535,610,310,122],[270,520,205,110]].forEach(([x,y,rx,ry])=>{ctx.beginPath();ctx.ellipse(x,y,rx,ry,-.08,0,Math.PI*2);ctx.fill()});
 ctx.fillStyle=mixColor('#b4db92','#769178',tone.night);[[585,470,66,34],[468,371,55,28],[590,682,48,22],[500,712,39,18]].forEach(([x,y,rx,ry])=>{ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill()});
 // 边缘树带；轻微摆动提供环境呼吸感。
 const trees=[[150,118,13],[177,102,11],[204,92,14],[252,76,12],[310,69,10],[708,68,12],[762,76,14],[820,83,11],[882,92,13],[944,108,12],[1010,144,14],[1060,202,12],[1082,270,14],[1092,345,12],[1084,420,14],[1067,500,11],[1040,570,14],[1002,636,12],[930,686,13],[860,712,11],[780,728,13],[400,735,12],[330,716,14],[250,684,12],[196,642,14],[160,584,11],[145,505,13],[140,418,11],[146,340,13],[153,270,11]];
 trees.forEach(([x,y,s],i)=>drawTree(x,y,s,now,tone,i));
 // 水岸积水事件：水面向信息楼—足球场道路扩散。
 if(state.events.has('flood')){const pulse=.5+.5*Math.sin(now*3);ctx.fillStyle=`rgba(73,176,215,${.22+pulse*.08})`;ctx.beginPath();ctx.moveTo(82,212);ctx.bezierCurveTo(178,206,245,250,303,303);ctx.bezierCurveTo(326,343,326,405,286,438);ctx.bezierCurveTo(196,432,132,389,94,330);ctx.closePath();ctx.fill();ctx.strokeStyle=`rgba(255,119,92,${.58+pulse*.25})`;ctx.lineWidth=4;ctx.setLineDash([10,8]);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#9d332e';ctx.font='800 14px ui-rounded,sans-serif';ctx.fillText('滨水积水风险区',165,286)}
 return tone;
}
function drawRoads(now,tone){
 const primary=new Set(['01|02','02|13','05B|06','06|13','04|05R','04|09','09|10','13|14']);
 edgePairs.forEach(([a,b])=>{const main=primary.has(edgeKey(a,b)),closed=state.closed.has(edgeKey(a,b));ctx.lineCap='round';ctx.strokeStyle='rgba(35,73,77,.16)';ctx.lineWidth=main?18:13;ctx.beginPath();ctx.moveTo(nodes[a].x+3,nodes[a].y+4);ctx.lineTo(nodes[b].x+3,nodes[b].y+4);ctx.stroke();ctx.strokeStyle=closed?'#f57a6f':tone.road;ctx.lineWidth=main?14:9;ctx.beginPath();ctx.moveTo(nodes[a].x,nodes[a].y);ctx.lineTo(nodes[b].x,nodes[b].y);ctx.stroke();const tf=trafficFactor(a,b);ctx.strokeStyle=closed?'#a52f2b':state.layers.traffic?(tf>1.35?'#e88a5b':tf>1.15?'#d7b85a':'rgba(118,151,151,.55)'):'rgba(118,151,151,.42)';ctx.lineWidth=2;ctx.stroke();if(state.running&&!closed){ctx.save();ctx.strokeStyle='rgba(255,255,255,.72)';ctx.lineWidth=2;ctx.setLineDash([2,18]);ctx.lineDashOffset=-(now*17)%20;ctx.stroke();ctx.restore()}if(closed){const x=(nodes[a].x+nodes[b].x)/2,y=(nodes[a].y+nodes[b].y)/2;ctx.fillStyle='#fff';ctx.font='800 18px sans-serif';ctx.textAlign='center';ctx.fillText('×',x,y+6)}})
}
function drawLamps(now,tone){if(tone.night<.05)return;const pulse=.88+.12*Math.sin(now*2);[[520,414],[640,421],[768,405],[817,454],[742,548],[572,600],[390,497],[345,330]].forEach(([x,y])=>{const glow=ctx.createRadialGradient(x,y,1,x,y,18);glow.addColorStop(0,`rgba(255,226,135,${tone.night*pulse*.58})`);glow.addColorStop(1,'rgba(255,226,135,0)');ctx.fillStyle=glow;ctx.beginPath();ctx.arc(x,y,18,0,Math.PI*2);ctx.fill();ctx.strokeStyle=mixColor('#496a6a','#263e49',tone.night);ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x,y+7);ctx.lineTo(x,y-4);ctx.stroke();ctx.fillStyle='#ffe28a';ctx.beginPath();ctx.arc(x,y-5,3,0,Math.PI*2);ctx.fill()})}
function draw(){const now=performance.now()/1000;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.save();ctx.translate(state.view.ox,state.view.oy);ctx.scale(state.view.scale,state.view.scale);const tone=drawTerrain(now),p=period(state.time);if(state.layers.mobility)Object.values(nodes).forEach(n=>{let x=['teach','dorm','hub','market'].includes(n.type)?p.mobility:.25;if(n.type==='sport'&&state.time>960)x=.55;drawHeat(n,x,'rgba(255,122,99,.25)')});drawRoads(now,tone);if(state.layers.orders)pendingOrders().forEach(o=>drawHeat(nodes[o.dest],.55,'rgba(255,69,72,.42)'));Object.entries(nodes).forEach(([id,n])=>drawBuilding(id,n));drawLamps(now,tone);state.vehicles.forEach(drawVehicle);if(state.layers.security&&state.quarantine.some(o=>o.status==='quarantined')){ctx.fillStyle='#fb6e68';ctx.beginPath();ctx.arc(nodes['24'].x+35,nodes['24'].y-27,11,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.font='800 13px sans-serif';ctx.textAlign='center';ctx.fillText('!',nodes['24'].x+35,nodes['24'].y-22)}ctx.restore();requestAnimationFrame(draw)}
function renderAll(){renderTime();renderPanels();renderCompare()}
function tick(now){if(!tick.last)tick.last=now;const dt=Math.min(.1,(now-tick.last)/1000);tick.last=now;if(state.running&&state.time<1200){const simMin=dt*state.speed;state.time+=simMin;state.vehicles.forEach(v=>updateVehicle(v,simMin));if(state.time-state.lastOrderMinute>=10){state.lastOrderMinute=state.time;generateOrders();renderAll()}if(state.time>=1140){state.running=false;$('#playBtn').textContent='▶ 开始';addLog('19:00车辆停运，本局自动结算');settle()}else if(Math.floor(state.time)%2===0)renderAll()}requestAnimationFrame(tick)}
function settle(){state.running=false;$('#playBtn').textContent='▶ 开始';const delivered=state.metrics.delivered,rate=delivered?state.metrics.ontime/delivered*100:100,empty=state.metrics.distance?100*(1-state.metrics.loadedDistance/state.metrics.distance):0;$('#resultScore').textContent=score();$('#resultTitle').textContent=score()>=1200?'优秀：调度稳定且低碳':score()>=900?'良好：仍有优化空间':'需要调整调度策略';$('#resultBreakdown').innerHTML=`<div>完成订单<b>${delivered}</b></div><div>准时率<b>${rate.toFixed(0)}%</b></div><div>累计能耗<b>${state.metrics.energy.toFixed(2)} kWh</b></div><div>空驶率<b>${empty.toFixed(0)}%</b></div>`;$('#resultDialog').showModal()}
$('#playBtn').onclick=()=>{state.running=!state.running;$('#playBtn').textContent=state.running?'Ⅱ 暂停':'▶ 开始';addLog(state.running?'仿真开始运行':'仿真已暂停')};$('#speedSelect').onchange=e=>state.speed=+e.target.value;$('#resetBtn').onclick=reset;$('#settleBtn').onclick=settle;$('#closeResult').onclick=()=>$('#resultDialog').close();$('#autoDispatch').onclick=autoDispatch;$('#refreshCompare').onclick=()=>{renderCompare();addLog('已按当前路况重新测算三种策略')};$('#reviewAttack').onclick=reviewAttack;$('#clearLog').onclick=()=>$('#log').innerHTML='';
$$('[data-strategy]').forEach(b=>b.onclick=()=>{state.strategy=b.dataset.strategy;$$('[data-strategy]').forEach(x=>x.classList.toggle('active',x===b));renderPanels();renderCompare()});$$('[data-event]').forEach(b=>b.onclick=()=>triggerEvent(b.dataset.event,b));$$('[data-layer]').forEach(c=>c.onchange=()=>state.layers[c.dataset.layer]=c.checked);$('#timeSlider').oninput=e=>{state.time=+e.target.value;renderAll()};$('#fitMap').onclick=()=>state.view={scale:1,ox:0,oy:0};
canvas.addEventListener('wheel',e=>{e.preventDefault();state.view.scale=Math.max(.75,Math.min(1.7,state.view.scale*(e.deltaY<0?1.08:.92)))},{passive:false});canvas.addEventListener('pointerdown',e=>{state.drag={x:e.clientX,y:e.clientY,ox:state.view.ox,oy:state.view.oy,moved:false};canvas.setPointerCapture(e.pointerId);canvas.classList.add('dragging')});canvas.addEventListener('pointermove',e=>{if(!state.drag)return;const dx=e.clientX-state.drag.x,dy=e.clientY-state.drag.y;if(Math.hypot(dx,dy)>3)state.drag.moved=true;state.view.ox=state.drag.ox+dx*(canvas.width/canvas.clientWidth);state.view.oy=state.drag.oy+dy*(canvas.height/canvas.clientHeight)});canvas.addEventListener('pointerup',e=>{if(state.drag&&!state.drag.moved){const r=canvas.getBoundingClientRect(),x=((e.clientX-r.left)*canvas.width/r.width-state.view.ox)/state.view.scale,y=((e.clientY-r.top)*canvas.height/r.height-state.view.oy)/state.view.scale;let hit=null,best=40;Object.entries(nodes).forEach(([id,n])=>{const d=Math.hypot(x-n.x,y-n.y);if(d<best){best=d;hit=[id,n]}});if(hit){const model=hit[1].model?` · ${hit[1].model}`:'';$('#mapTip').textContent=`${hit[0]==='05R'?'05行政':hit[0]==='05B'?'05女寝':hit[0]} ${hit[1].name} · ${typeLabels[hit[1].type]}${model} · ${hit[1].note}`}}state.drag=null;canvas.classList.remove('dragging')});
window.__simulationQA={nodes:()=>Object.keys(nodes),snapshot:()=>({time:state.time,orders:state.orders.map(o=>({id:o.id,status:o.status})),vehicles:state.vehicles.map(v=>({id:v.id,status:v.status,battery:v.battery})),metrics:{...state.metrics},score:score()}),dijkstra:(a,b)=>dijkstra(a,b)};
reset();requestAnimationFrame(draw);requestAnimationFrame(tick);
